- name: install python packages
  become: true
  apt: cache_valid_time={{ apt_cache_seconds }}
       name={{ item }}
       state=latest
       update_cache=yes
  with_items:
    - python3
    - python3-pip
    - python3-dev
    - python3-venv