- name: install nginx
  become: true
  apt: name=nginx state=present

- name: remove default nginx config
  become: true
  file: name=/etc/nginx/sites-enabled/default state=absent

- name: install system nginx config
  become: true
  template:
    src: templates/django-server
    dest: /etc/nginx/sites-enabled/django-server